config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  resources :walks, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :walk_reviews, only: [ :new, :create]
    resources :steps, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :publicwalks, only: :index
  resources :reviews, only: [:destroy]
end

app/models/advantage.rb
class Advantage < ApplicationRecord
  has_many :walk_advantages, dependent: :destroy
  has_many :walks, through: :walk_advantages, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/disadvantage.rb
class Disadvantage < ApplicationRecord
  has_many :walk_disadvantages, dependent: :destroy
  has_many :walks, through: :walk_disadvantages, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :walk

  validates :name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :walks
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
end

app/models/walk.rb
class Walk < ApplicationRecord
  belongs_to :user
  has_many :walk_advantages, dependent: :destroy
  has_many :walk_disadvantages, dependent: :destroy
  has_many :advantages, through: :walk_advantages, dependent: :destroy
  has_many :disadvantages, through: :walk_disadvantages, dependent: :destroy
  has_many_attached :photos, dependent: :destroy
  has_many :walk_reviews, dependent: :destroy
  has_many :steps, dependent: :destroy

  accepts_nested_attributes_for :steps

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :title, :address, presence: true
  validates :photos, limit: { min: 0, max: 3 }
  validates :photos, content_type: %i[png jpg jpeg]
  validates :photos, size: { between: ((1.kilobyte)..(10.megabytes)) }
  validates :content, length: { maximum: 900 }
end

app/models/walk_advantage.rb
class WalkAdvantage < ApplicationRecord
  belongs_to :walk
  belongs_to :advantage
end

app/models/walk_disadvantage.rb
class WalkDisadvantage < ApplicationRecord
  belongs_to :walk
  belongs_to :disadvantage
end

app/models/walk_review.rb
class WalkReview < ApplicationRecord
  belongs_to :walk

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0,
                                                     less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address photo])
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || walks_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @walks = Walk.where(status: "public").sample(6)
  end
end

app/controllers/publicwalks_controller.rb
class PublicwalksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @walks = Walk.where(status: "public")
    @markers = @walks.geocoded.map do |walk|
      {
        lat: walk.latitude,
        lng: walk.longitude,
        info_window: render_to_string(partial: "info_window", locals: { walk: walk }),
        image_url: helpers.asset_url("green-logo.png")
      }
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :find_walk, only: %i[index new create destroy edit update]


  def index
    @steps = Step.where(walk: @walk)
    @step = Step.new
  end

  def new
    @step = Step.new
  end

  def create
    @step = Step.new(step_params)
    @step.walk = @walk
    if @step.save
      if request.referrer.include?("steps")
        redirect_to walk_steps_path(@walk), status: :see_other
      else
        redirect_to walk_path(@walk), status: :see_other
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @step = Step.find(params[:id])
  end

  def update
    @step = Step.find(params[:id])
    if @step.update(step_params)
      redirect_to walk_steps_path(@walk)
    else
      redirect_to edit_walk_step_path(@walk, @step)
    end
  end

  def destroy
    @step = Step.find(params[:id])
    @step.destroy!
    if request.referrer.include?("steps")
      redirect_to walk_steps_path(@walk), status: :see_other
    else
      redirect_to walk_path(@walk), status: :see_other
    end
  end

  private

  def step_params
    params.require(:step).permit(:name, :latitude, :longitude, :walk_id)
  end

  def find_walk
    @walk = Walk.find(params[:walk_id])
  end
end

app/controllers/walk_reviews_controller.rb
class WalkReviewsController < ApplicationController
  before_action :find_walk, only: %i[new create destroy]

  def new
    @walk_review = WalkReview.new
  end

  def create
    @walk_review = WalkReview.new(walk_review_params)
    @walk_review.walk = @walk
    if @walk_review.save!
      redirect_to walk_path(@walk)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @walk_review = WalkReview.find(params[:id])
    @walk_review.destroy
    redirect_to walk_path(@walk_review.walk), status: :see_other
  end

  private

  def walk_review_params
    params.require(:walk_review).permit(:rating, :content, :walk_id)
  end

  def find_walk
    @walk = Walk.find(params[:walk_id])
  end
end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
  before_action :find_walk, only: %i[show edit update destroy]

  def index
    @walks = Walk.where(user: current_user).order('LOWER(title)')
    @walk = Walk.new
    @markers = @walks.geocoded.map do |walk|
      {
        lat: walk.latitude,
        lng: walk.longitude,
        info_window: render_to_string(partial: "info_window", locals: { walk: walk }),
        image_url: helpers.asset_url("green-logo.png")
      }
    end
    @homemarker = [lat: current_user.latitude,
                   lng: current_user.longitude,
                   info_window: render_to_string(partial: "info_window_home", locals: { user: current_user }),
                   image_url: helpers.asset_url("homemarker.png")]
  end

  def show
    @step = Step.new
    @average_rating = average_rating(@walk)
    @steps = @walk.steps
    @markers = @walk.steps.map do |step|
      {
        lat: step.latitude,
        lng: step.longitude,
        info_window_step: render_to_string(partial: "info_window_step", locals: { step: step }),
        image_url: helpers.asset_url("stepmarker.png")
      }
    end
  end

  def new
    @walk = Walk.new
    @walk.steps.build
  end

  def create
    @walk = Walk.new(walk_params)
    @walk.user_id = current_user.id
    if @walk.save
      redirect_to walk_path(@walk)
    else
      redirect_to walks_path
    end
  end

  def edit
    @walk.num_km = @walk.num_km.to_f / 1000
    # debug(params)
  end

  def update
    if @walk.update(walk_params)
      redirect_to walk_path(@walk)
    else
      redirect_to edit_walk_path(@walk)
    end

  end

  def destroy
    @walk.destroy!
    redirect_to walks_path, status: :see_other
  end

  private

  def average_rating(walk)
    average_rating = 0
    WalkReview.where(walk_id: walk.id).each do |walk_review|
      average_rating += walk_review.rating
    end
    average_rating /= WalkReview.where(walk_id: walk.id).count.to_f
  end

  def walk_params
    paramsbis ||= params.require(:walk).permit(:title, :num_km, :duration, :rating, :address, :date, :content, :user_id, :status,
                                 :link, steps_attributes: %i[name latitude longitude], advantage_ids: [],
                                 disadvantage_ids: [], photos: [])
    paramsbis[:num_km] = paramsbis[:num_km].to_f * 1000
    paramsbis
  end

  def find_walk
    @walk = Walk.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TraceTaBalade</title>
    <%= favicon_link_tag asset_path('green-logo.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="navbar">
  <div class="nom-logo">
    <img src="https://res.cloudinary.com/dsp76osnf/image/upload/v1666616208/logo-triangle_wkbdhf.png" alt="logo">
  </div>

  <div class="buttons-navbar">
    <div class="bg-btn-nav <%= "prod" if request.path == "/"%>">
      <%= link_to root_path do %>
        <p>Accueil</p>
      <% end %>
    </div>
    <div class="bg-btn-nav <%= "prod" if request.path == "/public-walks"%>">
      <%= link_to publicwalks_path do %>
        <p>Les balades partagées</p>
      <% end %>
    </div>
    <% if current_user %>
    <div class="bg-btn-nav <%= "prod" if request.path == "/walks"%>">
      <%= link_to walks_path do %>
        <p>Mes balades</p>
      <% end %>
    </div>
    <% else %>
    <div class="bg-btn-nav <%= "prod" if request.path == "/new_user_session"%>">
      <%= link_to new_user_session_path do %>
        <p>Connexion</p>
      <% end %>
    </div>
    <% end %>
    <div class="bg-btn-nav <%= "prod" if request.path == "/contact"%>">
      <%= link_to root_path do %>
        <p class="<%= "prod" if request.path == "/contact" %>">Contact</p>
      <% end %>
    </div>
  </div>
</div>

<div class="banner" >
  <%= link_to "Rejoins-nous !", new_user_registration_path %>
</div>

<div class="my-home-container">
  <h2>Pourquoi rejoindre "Trace ta balade" ?</h2>
  <div class="arg">
    <div class="arg-bis">
      <%= image_tag("https://res.cloudinary.com/dsp76osnf/image/upload/v1668506594/paw_hwc6qr.png") %>
      <p>Regrouper toutes les balades que tu aimes sur un seul site</p>
    </div>
    <div class="arg-bis">
        <%= image_tag("https://res.cloudinary.com/dsp76osnf/image/upload/v1668506594/share_zwemvm.png") %>
        <p>Enregistrer des balades et les partager ... ou pas</p>
    </div>
    <div class="arg-bis">
        <%= image_tag("https://res.cloudinary.com/dsp76osnf/image/upload/v1668506594/search_ykaq5q.png") %>
        <p>Découvrir de nouvelles balades, partagées par la communauté</p>
    </div>
  </div>
  <h2>Quelques balades présentes sur "Trace ta balade" :</h2>
  <div class="sample-card">
    <div class="walks" >
        <% unless @walks == nil %>
          <% @walks.each do |w| %>
            <div class="walk-card <%= "public" if w.status == "public"%>">
              <div class="img-card">
                <% if w.photos.present? %>
                  <% if w.status.present? %>
                    <p class="status"><%= w.status%></p>
                  <% end %>
                  <%= cl_image_tag w.photos.first.key %>
                <% else %>
                    <% if w.status.present? %>
                      <p class="status"><%= w.status%></p>
                    <% end %>
                  <img src="https://res.cloudinary.com/dsp76osnf/image/upload/v1664806325/Group_1_omxsxo.png" alt="image">
                <% end %>
              </div>
              <div class="text-card">
                <p><%= w.title %></p>
                <p class="address"><%= w.address %></p>
                <div class="num-card">
                  <% if w.num_km.present? %>
                    <p><i class="fa-sharp fa-solid fa-road"></i><%= (w.num_km)/1000.to_f %>km</p>
                  <% end %>
                  <% if w.duration.present? %>
                    <p><i class="fa-solid fa-clock"></i><%= (w.duration/60.to_f) %>h</p>
                  <% end %>
                  <% if w.rating.present? %>
                    <p><i class="fa-sharp fa-solid fa-star"></i><%= w.rating %>/5</p>
                  <% end %>
                </div>
                <%= link_to "Voir la balade", walk_path(w), target: :_blank %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <div class="review">
    <h2>Vos témoignages</h2>
    <p><%= Review.order('RANDOM()').first.content %></p>
  </div>
</div>

<div class="footer">
  <%= link_to "https://www.instagram.com/les_aleas_d_une_vie_de_chien/?hl=fr", target: :_blank do %>
    <i class="fa-brands fa-instagram"></i>
  <% end %>
  <%= link_to "https://github.com/JeanneEnnaej", target: :_blank do %>
    <i class="fa-brands fa-github"></i>
  <% end %>
  <%= link_to "https://www.linkedin.com/in/jeanne-desmier-6061a3a7/", target: :_blank do %>
    <i class="fa-brands fa-linkedin"></i>
  <% end %>
</div>

app/views/publicwalks/_footer.html.erb
<div class="footer">
  <%= link_to "https://www.instagram.com/les_aleas_d_une_vie_de_chien/?hl=fr", target: :_blank do %>
    <i class="fa-brands fa-instagram"></i>
  <% end %>
  <%= link_to "https://github.com/JeanneEnnaej", target: :_blank do %>
    <i class="fa-brands fa-github"></i>
  <% end %>
  <%= link_to "https://www.linkedin.com/in/jeanne-desmier-6061a3a7/", target: :_blank do %>
    <i class="fa-brands fa-linkedin"></i>
  <% end %>
</div>

app/views/publicwalks/_info_window.html.erb
<h2><%= walk.title %></h2>
<p><%= walk.address %></p>
<p><%= link_to "voir la balade", walk_path(walk) %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/steps/_form_edit_step.html.erb
<%= simple_form_for [walk, step] do |f| %>
  <p>Nom de l'étape :</p>
  <%= f.input :name, label: false  %>
  <p>Latitude:</p>
  <%= f.input :latitude, label: false  %>
  <p>Longitude:</p>
   <%= f.input :longitude, label: false  %>
  <%= f.button :submit, "Modifier" %>
<% end %>

app/views/steps/index.html.erb
<%= render "walks/navbar" %>

<div class="new-container">

<h1>Bienvenue sur la creation de votre itinéraire</h1>

  <% @steps.each do |step| %>
    <%= step.name %>
    <%= step.latitude %>
    <%= step.longitude %>
    <%= link_to "Modifier l'étape", edit_walk_step_path(@walk, step) %>
    <%= link_to "Supprimer l'étape", walk_step_path(@walk, step), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <% end %>


  <h4>Créer une nouvelle étape</h4>
  <%= render "form_new_step", walk:@walk, step:@step %>

  <%= link_to "Retourner sur la balade", walk_path(@walk) %>
</div>


<%= render "walks/footer" %>

app/views/walks/_info_window_home.html.erb
<h2>Maison de <%= current_user.first_name %></h2>
<p><%= current_user.address %></p>

app/views/walks/_info_window_step.html.erb
<p><%= step.name %></p>
<p><%= link_to "Supprimer l'étape", walk_step_path(@walk, step), data: {turbo_method: :delete, turbo_confirm: "Etes vous sûr de vouloir supprimer cette étape?"} %></p>

app/views/walks/_navbar.html.erb
<div class="navbar">
  <div class="nom-logo">
    <img src="https://res.cloudinary.com/dsp76osnf/image/upload/v1666616208/logo-triangle_wkbdhf.png" alt="logo">
  </div>

  <div class="buttons-navbar">
    <div class="bg-btn-nav <%= "prod" if request.path == "/"%>">
      <%= link_to root_path do %>
        <p>Home</p>
      <% end %>
    </div>
    <div class="bg-btn-nav <%= "prod" if request.path == "/publicwalks"%>">
      <%= link_to publicwalks_path do %>
        <p>Les balades partagées</p>
      <% end %>
    </div>
    <% if current_user %>
    <div class="bg-btn-nav <%= "prod" if request.path == "/walks"%>">
      <%= link_to walks_path do %>
        <p>Mes balades</p>
      <% end %>
    </div>
    <% else %>
    <div class="bg-btn-nav <%= "prod" if request.path == "/new_user_session"%>">
      <%= link_to new_user_session_path do %>
        <p>Connexion</p>
      <% end %>
    </div>
    <% end %>
    <div class="bg-btn-nav <%= "prod" if request.path == "/contact"%>">
      <%= link_to root_path do %>
        <p class="<%= "prod" if request.path == "/contact" %>">Contact</p>
      <% end %>
    </div>
  </div>
</div>

app/views/walks/index.html.erb
<%= render "navbar" %>


<div class="my-container" data-controller="show">
 <h4><i class="fa-solid fa-paw"></i> Tu trouvera ici toutes les balades que tu as enregistré sur <em>Trace ta balade</em> <i class="fa-solid fa-paw"></i></h2>
  <div class="card-map-container">
    <div class="card-container">
      <span class="add-walk"><%= link_to "+ Nouvelle balade +", new_walk_path %></span>
      <div class="walks" >
        <% unless @walks == nil %>
          <% @walks.each do |w| %>
            <div class="walk-card <%= "public" if w.status == "public"%>">
              <div class="img-card">
                <% if w.photos.present? %>
                  <% if w.status.present? %>
                    <p class="status"><%= w.status%></p>
                  <% end %>
                  <%= cl_image_tag w.photos.first.key %>
                <% else %>
                    <% if w.status.present? %>
                      <p class="status"><%= w.status%></p>
                    <% end %>
                  <img src="https://res.cloudinary.com/dsp76osnf/image/upload/v1664806325/Group_1_omxsxo.png" alt="image">
                <% end %>
              </div>
              <div class="text-card">
                <p><%= w.title %></p>
                <p class="address"><%= w.address %></p>
                <div class="num-card">
                  <% if w.num_km.present? %>
                    <p><i class="fa-sharp fa-solid fa-road"></i><%= (w.num_km)/1000.to_f %>km</p>
                  <% end %>
                  <% if w.duration.present? %>
                    <p><i class="fa-solid fa-clock"></i><%= (w.duration/60.to_f) %>h</p>
                  <% end %>
                  <% if w.rating.present? %>
                    <p><i class="fa-sharp fa-solid fa-star"></i><%= w.rating %>/5</p>
                  <% end %>
                </div>
                <%= link_to "Voir la balade", walk_path(w), target: :_blank %>
                <div>
                  <%= link_to walk_path(w),data: {turbo_method: :delete, turbo_confirm: "Etes vous sur?"} do %>
                    <p><i class="fa-solid fa-trash-can"></i></p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-homemarker-value="<%= @homemarker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete}%>
</div>

<%= render "footer" %>

app/views/walks/show.html.erb
<%= render "navbar" %>


<div class="my-container" data-controller="show">
  <h4> La balade : "<%= @walk.title %>"</h3>
  <div class="show-container">
    <div class="show-card" data-controller="img">
      <div class="img-card">
        <% if @walk.photos.present? %>
          <% if @walk.status.present? %>
            <p class="status"><%= @walk.status%></p>
          <% end %>
          <span data-action="click->img#showPopup"><%= cl_image_tag @walk.photos.first.key %></span>
          <p class="indication">Cliquez sur la photo pour voir toutes les photos</p>
        <% else %>
          <% if @walk.status.present? %>
            <p class="status"><%= @walk.status%></p>
          <% end %>
          <img src="https://res.cloudinary.com/dsp76osnf/image/upload/v1664806325/Group_1_omxsxo.png" alt="image" data-action="click->img#showPopup">
        <% end %>
        <% if @walk.photos.present? %>
          <div class="img-popup display-none" data-img-target="popup" >
            <div class="img-popup-card">
              <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <%= cl_image_tag @walk.photos.first.key, class:"d-block w-50 mx-auto "%>
                  </div>
                  <% if @walk.photos[1].present? %>
                    <div class="carousel-item">
                      <%= cl_image_tag @walk.photos[1].key, class:"d-block w-50 mx-auto"%>
                    </div>
                  <% end %>
                  <% if @walk.photos[2].present? %>
                    <div class="carousel-item">
                      <%= cl_image_tag @walk.photos[2].key, class:"d-block w-50 mx-auto"%>
                    </div>
                  <% end %>
                  <% if @walk.photos[3].present? %>
                    <div class="carousel-item">
                      <%= cl_image_tag @walk.photos[3].key, class:"d-block w-50 mx-auto"%>
                    </div>
                  <% end %>
                  <% if @walk.photos[4].present? %>
                    <div class="carousel-item">
                      <%= cl_image_tag @walk.photos[4].key, class:"d-block w-50 mx-auto"%>
                    </div>
                  <% end %>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            </div>
            <i class="fa-solid fa-xmark cross" data-action="click->img#showPopup"></i>
          </div>
        <% end %>
      </div>

      <div class="show-card-text">
        <div class="info">
          <% if @walk.date.present? %>
            <p>Balade du <%= @walk.date.strftime("%d/%m/%Y") %></p>
          <% end %>
          <p>Adresse : <%= @walk.address %></p>
        </div>
        <div class="details">
          <% if @walk.num_km.present?  %>
            <p><i class="fa-sharp fa-solid fa-road"></i> <%= (@walk.num_km)/1000.to_f %>km</p>
          <% end %>
          <% if @walk.duration.present? %>
            <p><i class="fa-solid fa-clock"></i> <%= ((@walk.duration)/60.to_f) %>h</p>
          <% end %>
          <% if current_user.id == @walk.user_id %>
            <% if @walk.rating.present? %>
              <p>Note perso :<i class="fa-sharp fa-solid fa-star"></i> <%= @walk.rating %>/5</p>
            <% end %>
            <% if @average_rating.nan? == false %>
              <p>Note publique :<i class="fa-sharp fa-solid fa-star"></i><%= @average_rating.round(1) %>/5</p>
            <% end %>
          <% end %>
        </div>
        <% if @walk.content.present? %>
          <span class="content-walk"><%= @walk.content %></span>
        <% end %>
        <br>
        <% if @walk.link.present? %>
          <span class="extern-link2"><%= link_to "Lien vers la rando", "#{@walk.link}", target: :_blank %></span>
        <% end %>
        <div class="liste">
          <div class="advantage">
          <p> Les points positifs de la balade :</p>
          <ul>
            <% unless @walk.advantages == nil %>
              <% @walk.advantages.each do |a| %>
                <li><%= a.name %></li>
              <% end %>
            <% end %>
          </ul>
          </div>
          <div class="disadvantage">
            <p> Les points négatifs de la balade :</p>
            <ul>
              <% unless @walk.disadvantages == nil %>
                <% @walk.disadvantages.each do |a| %>
                  <li><%= a.name %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="itinerary-container">
   <% if @walk.steps.present? %>
      <div class="step-map"
        data-controller="step-map"
        data-step-map-markers-value="<%= @markers.to_json %>"
        data-step-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        <div class="form-map-step">
          <p data-action="click->step-map#showStepForm">Ajouter une étape</p>
          <div data-step-map-target="stepForm">
            <%= render  "steps/form_new_step", walk:@walk, step:@step %>
          </div>
        </div>

      </div>
      <div class="steps-list">
        <ul>
        <% s=0 %>
        <% @walk.steps.each do |step| %>
          <li>Etape <%= s+=1 %> : <%= step.name %> / latitude :<%= step.latitude %> longitude :<%= step.longitude %></li>
        <% end %>
        </ul>
        <% if current_user.id == @walk.user_id %>
          <%= link_to "Modifier l'itinéraire de la balade", walk_steps_path(@walk), class: "edit-itinerary"%>
        <% end %>
      </div>
    <% else %>
      <% if current_user.id == @walk.user_id %>
        <div class="new-itinerary">
          <p>Créez un itinéraire pour plus de visibilité !</p>
          <%= link_to "Créer un itinéraire de balade", walk_steps_path(@walk), class: "create-itinerary"%>
        </div>
      <% else %>
        <p><%= @walk.user.first_name %> n'a pas créé d'itinéraire pour cette balade</p>
      <% end %>
    <% end %>
  </div>

  <div class="walk-review">
    <h4>Commentaires</h4>
    <% if @walk.walk_reviews == [] %>
      <p>Il n'y a pas encore de commentaire sur cette balade, lancez vous !</p>
    <% else %>
      <ul>
        <% @walk.walk_reviews.each do |walk_review| %>
          <p><li><%= walk_review.content %> / note : <%= walk_review.rating %></li></p>
        <% end %>
      </ul>
    <% end %>
    <%= link_to "Noter la balade", new_walk_walk_review_path(@walk) %>
  </div>

  <div class="show-link">
    <% if current_user.id == @walk.user_id %>
      <%= link_to "Modifier la balade", edit_walk_path(@walk) %>
    <% end %>
    <% if current_user.id == @walk.user_id %>
      <%= link_to "Supprimer la balade", walk_path(@walk), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <% end %>
    <%= link_to "Retourner à la liste", walks_path %>
  </div>
</div>



<%= render "footer" %>